config/routes.rb
Livezen::Application.routes.draw do
  root :to => "users#show"

  resources :users, :lists, :tasks
  resources :sessions, :only => [ :new, :create, :destroy ]

  match "signup" => "users#new"
  match "login" => "sessions#new"
  match "logout" => "sessions#destroy"
  match "profile" => "users#show"
  match "tasks/:id/complete" => "tasks#complete", :as => "complete"
  match "lists/:id/:status" => "lists#show"

  get "list_shares/index"
  get "sessions/destroy"

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :list_shares, :dependent => :destroy
	has_many :users, :through => :list_shares
  has_many :tasks, :dependent => :destroy
	attr_accessible :name

  after_create :make_owner

	validates :name, :presence => true

  protected

  def make_owner
    if (shares = ListShare.where(:list_id => @list.id, :user_id => current_user.id))
      ls = shares.first
      ls.owner = true
      ls.save!
    end
  end
end

app/models/list_share.rb
class ListShare < ActiveRecord::Base
	belongs_to :user
	belongs_to :list

	validates :list_id, :user_id, :presence => true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list
end

app/models/user.rb
class User < ActiveRecord::Base
	require 'bcrypt'
	attr_accessible :email, :password, :password_confirmation, :first_name, :last_name
	has_secure_password

	has_many :list_shares
	has_many :lists, :through => :list_shares
	
	validates_presence_of :password, :on => :create
	validates_presence_of :email

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/list_shares_controller.rb
class ListSharesController < ApplicationController
  def index
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :find_list, :only => [ :show, :edit, :update, :destroy ]

  def index
    @user = User.find(current_user.id)
    @lists = @user.lists
  end

  def show
    @task = Task.new

    # TODO reconsider the way status is handled here
    if params[:status].nil?
      @tasks = @list.tasks.where(:status => 1)
    elsif params[:status] == "all"
      @tasks = @list.tasks
    else
      @tasks = @list.tasks.where( :status => params[:status] )
    end
  end

  def new
  	@list = List.new
  end

  def edit
  end

  def create
  	@list = List.new(params[:list])
    @user = User.find(current_user.id)
    @list.users << @user
  	if @list.save
  		redirect_to lists_path, :notice => "List added"
  	else
  		render 'new'
  	end
  end

  def update
  	if @list.update_attributes(params[:list])
  		redirect_to list_url(@list), :notice => "List updated"
  	else
  		render 'edit'
  	end
  end

  def destroy
    @list.destroy
		redirect_to lists_url, :notice => "List deleted"
  end

  def find_list
  	@list = List.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	#force_ssl
	
	def new
	end

	def create
		# Railscast example did not need [:session][:email/password]
		# Tests fail without it
		user = User.find_by_email(params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to user_url(current_user.id), :notice => "Logged in"
		else
			flash[:error] =  "Invalid email or password"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :find_task, :only => [:show, :update, :edit, :complete]

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task])
    # TODO move status to model
    @task.status = 1

    if @task.save
      flash[:notice] = "Task added"
      redirect_to @task.list
    else
      flash[:error] = "Task did not save."
      render 'lists/show/#{@task.list_id}'
    end
  end

  def show
  end

  def update
    if @task.update_attributes
      flash[:success] = "Task updated"
      redirect_to @task
    else
      render 'edit'
    end
  end

  def edit
  end

  def find_task
    @task = Task.find(params[:id])
  end
  
  # TODO move to model
  def complete
    @task.update_attributes("status" => 3)
    redirect_to @task
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #force_ssl
  before_filter :redirect_user_if_not_logged_in, :except => [ :new, :create ]
  before_filter :find_user, :only => [ :show, :edit, :update ]

  def index
  	@users = User.all
  end

  def show
  end

  def new
  	@user = User.new
  end

  def edit
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
      flash[:success] = "Signup successful. Log in to access your account."
  		redirect_to login_url
  	else
  		render 'new'
  	end
  end

  def update
  	if @user.update_attributes
  		redirect_to @user, :notice => "Account updated"
  	else
  		render 'edit'
  	end
  end

  def find_user
    @user = User.find(current_user.id)
  end

  def redirect_user_if_not_logged_in
    redirect_to(login_url) if !current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def twitterized_type(type)
    case type
      when :alert
        "warning"
      when :error
        "error"
      when :notice
        "info"
      when :success
        "success"
      else
        type.to_s
    end
  end
end

app/helpers/list_shares_helper.rb
module ListSharesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def status_converter(int)
    int.to_s
    case int
      when "1"
        "Active"
      when "2"
        "In progress"
      when "3"
        "Completed"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!5
%html
  %head
    %title Livezen
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    .topbar
      .topbar-inner
        .container
          = link_to "LiveZen", root_path, :class => "brand"
          %ul.nav
            %li= link_to "Listable", lists_path
            // Can use li.active for the active app.
          
          %p.pull-right
            - if current_user
              = link_to current_user.email, profile_path
              = " - "
              = link_to "Logout", logout_path
            - else
              = link_to "Login", login_path

    .content
      =render :partial => "shared/flash_messages", :locals => {:flash => flash}
      = yield

app/views/list_shares/index.html.haml
%h1 ListShares#index
%p Find me in app/views/list_shares/index.html.haml

app/views/lists/edit.html.haml
%h2 Edit list

= form_for @list do |f|

  - if @list.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @list.errors.full_messages
          %li= message

  .field
    = f.label      :name
    = f.text_field :name
  .actions
    = f.submit :class => "btn primary"

app/views/lists/index.html.haml
%h1 Lists

.lists
  - @lists.each do |list|
    = link_to list.name, list
    %br

.actions
  = link_to "New list", new_list_path, :class => "btn primary"

app/views/lists/new.html.haml
= form_for @list do |f|

  - if @list.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @list.errors.full_messages
          %li= message
  %fieldset
    %legend New list
    .field
      = f.label      :name
      = f.text_field :name
    .actions
      = f.submit

app/views/lists/show.html.haml
%h2= @list.name

= link_to "Edit", edit_list_path(@list), :class => "btn"
= link_to "Delete", @list, :method => :delete, :confirm => "Delete #{@list.name}?", :class => "btn danger"
%p
%p


.status
  = link_to 'Active', list_path(@list, :status => 1)
  = " | "
  = link_to 'Completed', list_path(@list, :status => 3)
  = " | "
  = link_to "All", list_path(@list, :status => "all")




.tasks
  - @tasks.each do |task|
    = link_to task.name, task
    = status_converter(task.status)
    %br

%fieldset
  %legend New task
  = form_for @task do |f|

    - if @task.errors.any?
      .error_messages
        %h2 Form is invalid
        %ul
          - for message in @task.errors.full_messages
            %li= message

    .field
      = f.label      :name
      = f.text_field :name
      = f.hidden_field :list_id, :value => @list.id
    .actions
      = f.submit :class => "btn primary"

app/views/shared/_flash_messages.html.haml
- flash.each do |type, message|
  %div.alert-message.fade.in{ "data-alert" => "alert", :class => twitterized_type(type) }
    %a.close{:href => "#"} ×
    %p
      = message

app/views/tasks/edit.html.haml
%h2= @task.name

= form_for @task do |f|

  - if @task.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @task.errors.full_messages
          %li= message

  .field
    = f.label      :name
    = f.text_field :name
  .field
    = f.label :status
    = f.select :status, [["Active", 1], ["In progress", 2], ["Completed", 3]]
  .actions
    = f.submit :class => "btn primary"

app/views/tasks/show.html.haml
%h1= "#{@task.name} - (#{@task.status})"

= link_to "Complete", complete_path(@task), :class => "btn primary"
= link_to "Edit", edit_task_path(@task), :class => "btn"
= link_to "Delete", @task, :method => :delete, :confirm => "Delete #{@task.name}?", :class => "btn danger"

app/views/users/index.html.haml
%h1 Users#index
%p Find me in app/views/users/index.html.haml

app/views/users/new.html.haml
%h1 Sign up
.form-stacked
	= form_for @user do |f|

		- if @user.errors.any?
			.error_messages
				%h2 Form is invalid
				%ul
					- for message in @user.errors.full_messages
						%li= message

		.field
			= f.label				:first_name
			= f.text_field	:first_name
		.field
			= f.label				:last_name
			= f.text_field	:last_name
		.field
			= f.label 		 :email
			= f.text_field :email
		.field
			= f.label 				 :password
			= f.password_field :password
		.field
			= f.label 				 :password_confirmation
			= f.password_field :password_confirmation
		.actions
			= f.submit "Sign up"

app/views/users/show.html.haml
%h1 Apps

= link_to "Listable", lists_path